### ISSUE TITLE
Quick export does not work with local installation: WSGI Applications must yield bytes

### ISSUE THREAD

**Issue by arne-cl** [amir-zeldes/rstWeb#34]
When editing a tree in the structure editor and clicking on the `XML` button,
the browser will be redirected to `http://localhost:8080/quick_export`,
but no file is downloaded.

This is the traceback:
```
~/repos/rstWeb $ python start_local.py 
[08/Mar/2018:12:18:03] ENGINE Listening for SIGHUP.
[08/Mar/2018:12:18:03] ENGINE Listening for SIGTERM.
[08/Mar/2018:12:18:03] ENGINE Listening for SIGUSR1.
[08/Mar/2018:12:18:03] ENGINE Bus STARTING
[08/Mar/2018:12:18:03] ENGINE Started monitor thread 'Autoreloader'.
[08/Mar/2018:12:18:03] ENGINE Serving on http://127.0.0.1:8080
[08/Mar/2018:12:18:03] ENGINE Bus STARTED
{}
127.0.0.1 - - [08/Mar/2018:12:18:05] "GET / HTTP/1.1" 200 47 "" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:58.0) Gecko/20100101 Firefox/58.0"
{}
127.0.0.1 - - [08/Mar/2018:12:18:05] "GET /open HTTP/1.1" 200 5844 "http://localhost:8080/" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:58.0) Gecko/20100101 Firefox/58.0"
{'reset': u'', 'logging': u'', 'timestamp': u'', 'current_project': u'aaa', 'current_guidelines': u'**current_guidelines**', 'serve_mode': u'local', 'dirty': u'', 'current_doc': u'source.rs3'}
127.0.0.1 - - [08/Mar/2018:12:18:11] "POST /structure HTTP/1.1" 200 49930 "http://localhost:8080/open" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:58.0) Gecko/20100101 Firefox/58.0"
{'quickexp_project': u'aaa', 'quickexp_doc': u'source.rs3'}
127.0.0.1 - - [08/Mar/2018:12:18:24] "POST /quick_export HTTP/1.1" 200 4943 "http://localhost:8080/structure" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:58.0) Gecko/20100101 Firefox/58.0"
[08/Mar/2018:12:18:24] ENGINE ValueError('WSGI Applications must yield bytes',)
Traceback (most recent call last):
  File "/home/arne/.virtualenvs/rstweb/local/lib/python2.7/site-packages/cheroot/server.py", line 1152, in communicate
    req.respond()
  File "/home/arne/.virtualenvs/rstweb/local/lib/python2.7/site-packages/cheroot/server.py", line 974, in respond
    self.server.gateway(self).respond()
  File "/home/arne/.virtualenvs/rstweb/local/lib/python2.7/site-packages/cheroot/wsgi.py", line 135, in respond
    raise ValueError('WSGI Applications must yield bytes')
ValueError: WSGI Applications must yield bytes
```

**Comment by amir-zeldes** [comment]
Closed in 7f38e5c6d2d04e95e3dfc809a3dcb764df7385e1
