### ISSUE TITLE
Opening an rs3 file throws "IndexError: list index out of range"

### ISSUE THREAD

**Issue by arne-cl** [amir-zeldes/rstWeb#51]
Hi Amir,

when I try to open [this rs3 file](https://github.com/amir-zeldes/rstWeb/files/2609173/homework-killing.rs3.txt) in rstWeb (Python 2, current head of the master branch), I get the following error:

```
Traceback (most recent call last):
  File "/home/arne/.virtualenvs/rstweb/lib/python2.7/site-packages/cherrypy/_cprequest.py", line 631, in respond
    self._do_respond(path_info)
  File "/home/arne/.virtualenvs/rstweb/lib/python2.7/site-packages/cherrypy/_cprequest.py", line 690, in _do_respond
    response.body = self.handler()
  File "/home/arne/.virtualenvs/rstweb/lib/python2.7/site-packages/cherrypy/lib/encoding.py", line 221, in __call__
    self.body = self.oldhandler(*args, **kwargs)
  File "/home/arne/.virtualenvs/rstweb/lib/python2.7/site-packages/cherrypy/_cpdispatch.py", line 60, in __call__
    return self.callable(*self.args, **self.kwargs)
  File "start_local.py", line 51, in structure
    return structure_main("local","3",'local',**kwargs)
  File "/home/arne/repos/rstWeb-amir/structure.py", line 126, in structure_main
    def_multirel = get_def_rel("multinuc",current_doc, current_project)
  File "/home/arne/repos/rstWeb-amir/modules/rstweb_sql.py", line 242, in get_def_rel
    return rel_row[0][0]
IndexError: list index out of range
```

RSTTool renders the same file as follows:
![homework-killing rs3](https://user-images.githubusercontent.com/994109/48920651-66b03b80-ee9a-11e8-9045-3c0dc7508172.png)

Best,
Arne

**Comment by amir-zeldes** [comment]
Thanks for reporting this - the problem seems to be the fact that rstWeb attempts to fetch a default multinuclear relationship so it knows what to do if you should click the multinuc button (add a multinuc with the default relation = alphabetically lowest). But this document defines only satellite-nucleus relations in the header, so there is no 'default' multinuc relation to use. 

The easiest fix would be to hard-wire a behavior on none, so for example making the default multinuc relation be 'joint' or something, but this seems a little odd, since the header never defined that relation name. On the other hand, users who really want to not use multinucs can disable the multinuc button from the admin interface... Maybe a compromise is to generate a placeholder, like '--'.
