### ISSUE TITLE
Error in installing rstWeb - python3 - Ubuntu 20.04

### ISSUE THREAD

**Issue by erzaliator** [amir-zeldes/rstWeb#89]
After installing the requirements - `cherrypy` and `selenium` I run the following command - `bash rstweb_local.sh`
to get the following error:

Traceback (most recent call last):
  File "start_local.py", line 84, in &lt;module&gt;
    dispatcher = create_api_dispatcher()
  File "/home/kaveri/Research/phd_work_new/rst-tree-viz/rstWeb/api.py", line 488, in create_api_dispatcher
    dispatcher = cherrypy.dispatch.RoutesDispatcher()
  File "/home/kaveri/.local/lib/python3.8/site-packages/cherrypy/_cpdispatch.py", line 510, in __init__
    import routes
ModuleNotFoundError: No module named 'routes'

**Solution**
Installing the `routes` package via pip (`pip install routes`) solved the problem, it should probably be added to your dependencies in the README.

I am running python 3.8.10 on Ubuntu 20.04

**Comment by amir-zeldes** [comment]
That's odd, I've never had to explicitly install routes before... It works fine for me on Python 3.8 on Windows, and I don't even have routes installed:

```
$ py -3.8 -m pip show routes
WARNING: Package(s) not found: routes

$ py -3.8 start_local.py
[16/Nov/2021:10:45:41] ENGINE Listening for SIGTERM.
[16/Nov/2021:10:45:41] ENGINE Bus STARTING
[16/Nov/2021:10:45:41] ENGINE Set handler for console events.
[16/Nov/2021:10:45:41] ENGINE Started monitor thread 'Autoreloader'.
[16/Nov/2021:10:45:41] ENGINE Serving on http://127.0.0.1:8080
[16/Nov/2021:10:45:41] ENGINE Bus STARTED
```

I also tried this on a CentOS machine and could not reproduce the bug, also no routes installed:

```
[rstweb]$ python -m pip show routes
WARNING: Package(s) not found: routes

[rstweb]$ python start_local.py
[16/Nov/2021:10:50:33] ENGINE Bus STOPPING
[16/Nov/2021:10:50:33] ENGINE HTTP Server None already shut down
[16/Nov/2021:10:50:33] ENGINE No thread running for None.
[16/Nov/2021:10:50:33] ENGINE Bus STOPPED
[16/Nov/2021:10:50:33] ENGINE Bus EXITING
[16/Nov/2021:10:50:33] ENGINE Bus EXITED
[16/Nov/2021:10:50:33] ENGINE Listening for SIGTERM.
[16/Nov/2021:10:50:33] ENGINE Listening for SIGHUP.
[16/Nov/2021:10:50:33] ENGINE Listening for SIGUSR1.
[16/Nov/2021:10:50:33] ENGINE Bus STARTING
[16/Nov/2021:10:50:33] ENGINE Started monitor thread 'Autoreloader'.
[16/Nov/2021:10:50:33] ENGINE Serving on http://127.0.0.1:8099
[16/Nov/2021:10:50:33] ENGINE Bus STARTED
```

It's not hard for me to add routes to requirements, but I'd like to understand why this is working fine without requirements on two other OSs, but not on Ubuntu... @lgessler , sorry to bother you but do you have an Ubuntu machine running somewhere? If so, could you verify that running rstWeb's start_local.py with `cherrypy` installed but without `routes` leads to the crash above?

@erzaliator if you have any insight on the cause for this error I would be interested in fixing it - maybe it's some system configuration that causes cherrypy to run differently?

**Comment by lgessler** [comment]
Did the following in a clean Conda 4.9.2 env using Python 3.8 on Ubuntu 20.04.3 LTS:

```bash
pip install -r requirements.txt
bash rstweb_local.sh
```

No errors, am able to open the app fine. In my env, `CherryPy==18.6.1`. What is it in yours, @erzaliator? (Can check with `pip freeze | grep CherryPy`)

**Comment by lgessler** [comment]
Also, how exactly did you install `cherrypy`? I see `cherrypy` base doesn't require routes, but `cherrypy[routes_dispatcher]` does: https://github.com/cherrypy/cherrypy/blob/main/setup.py#L81

**Comment by erzaliator** [comment]
I tried a clean virtualenv install and redid the installation. It worked correctly!

My previous pip env was littered with too many packages and it must've been an issue for it. Thank you for suggesting a clean install in a new environment.

Also, is there a reason why step 4 for Section "Local Installation" suggests running the code as `run rstweb_local.sh` instead of `bash rstweb_local.sh`?

**Comment by amir-zeldes** [comment]
Glad to hear it's working!

The word 'run' in there is just meant to be English, not a Linux command (notice it's not italicized, unlike the script name). There are many ways to run programs in a *nix environment, including bash, but also other methods, so we didn't think to list which one to use.
